imported /debian/ from 2.2.8+dfsg-0.1

diff --git a/debian/freeradius.init b/debian/freeradius.init
--- a/debian/freeradius.init
+++ b/debian/freeradius.init
@@ -8,27 +8,18 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Radius Daemon
+# Short-Description: Radius Daemon 
 # Description:       Extensible, configurable radius daemon
 ### END INIT INFO
-
-PROG="freeradius"
-PROGRAM="/usr/sbin/freeradius"
-PIDFILE="/var/run/freeradius/freeradius.pid"
-DESCR="FreeRADIUS daemon"
 
 set -e
 
 . /lib/lsb/init-functions
 
-test_freeradius_config() {
-  log_action_begin_msg "Checking $DESCR configuration"
-
-  out=`$PROGRAM -Cxl stdout $FREERADIUS_OPTIONS`; ret=$?
-  out=`echo "${out}" | tail -n 1 | sed 's/^\s*ERROR:\s*\(.*\)\s*$/\1/'`
-  log_action_end_msg $ret "$out"
-  return $ret
-}
+PROG="freeradius"
+PROGRAM="/usr/sbin/freeradius"
+PIDFILE="/var/run/freeradius/freeradius.pid"
+DESCR="FreeRADIUS daemon"
 
 if [ -r /etc/default/$PROG ]; then
   . /etc/default/$PROG
@@ -49,51 +40,37 @@ ret=0
 case "$1" in
         start)
                 log_daemon_msg "Starting $DESCR" "$PROG"
-
-                start_daemon -p "$PIDFILE" "$PROGRAM" $FREERADIUS_OPTIONS || ret=$?
+                start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PROGRAM -- $FREERADIUS_OPTIONS || ret=$?
                 log_end_msg $ret
+                exit $ret
                 ;;
-
         stop)
                 log_daemon_msg "Stopping $DESCR" "$PROG"
-
-                killproc -p "$PIDFILE" || ret=$?
+                if [ -f "$PIDFILE" ] ; then
+                  start-stop-daemon --stop --retry=TERM/30/KILL/5 --quiet --pidfile $PIDFILE || ret=$?
+                else 
+                  log_action_cont_msg "$PIDFILE not found"
+                  ret=0
+                fi
                 log_end_msg $ret
                 ;;
-
-        restart|force-reload)
-                test_freeradius_config || exit $?
-
+        restart)
                 $0 stop
                 $0 start
                 ;;
-
-        reload)
-                test_freeradius_config || exit $?
-
-                if status_of_proc -p "$PIDFILE" "$PROG" "$DESCR"; then
-                  log_daemon_msg "Reloading $DESCR" "$PROG"
-
+        reload|force-reload)
+                log_daemon_msg "Reloading $DESCR" "$PROG"
+                if [ -f "$PIDFILE" ] ; then
                   start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE || ret=$?
-                  log_end_msg $ret
+                else 
+                  log_action_cont_msg "$PIDFILE not found"
+                  ret=0
                 fi
+                log_end_msg $ret
                 ;;
-
-        configtest|testconfig)
-                test_freeradius_config || exit $?
-                ;;
-
-        debug)
-                $PROGRAM -X $FREERADIUS_OPTIONS
-                ;;
-
-        status)
-                status_of_proc -p "$PIDFILE" "$PROGRAM" "$PROG" && exit 0 || exit $?
-                ;;
-
         *)
-                echo "Usage: $0 start|stop|restart|force-reload|reload|configtest|debug|status"
-                exit 1
+                echo "Usage: $0 start|stop|restart|force-reload|reload"
+                exit 1 
                 ;;
 esac
 
